# Generated by Django 4.1.12 on 2023-12-14 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profilePicture",
        ),
    ]
