# Generated by Django 4.1.12 on 2023-12-15 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_customuser_profilepicture"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltask",
            name="end_by",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2023, 12, 15, 17, 25, 20, 258053, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
