# Generated by Django 4.1.12 on 2023-12-10 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Null", max_length=255)),
                ("members", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="TeamTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskName", models.CharField(default="Null", max_length=255)),
                ("taskDescription", models.CharField(default="Null", max_length=1000)),
                (
                    "taskStatus",
                    models.CharField(
                        choices=[
                            ("INCOMPLETE", "INCOMPLETE"),
                            ("ONGOING", "ONGOING"),
                            ("COMPLETE", "COMPLETE"),
                        ],
                        default="Null",
                        max_length=30,
                    ),
                ),
                (
                    "taskImportance",
                    models.CharField(
                        choices=[
                            ("REGULAR", "REGULAR"),
                            ("IMPORTANT", "IMPORTANT"),
                            ("URGENT", "URGENT"),
                        ],
                        default="Null",
                        max_length=30,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.team"
                    ),
                ),
            ],
        ),
    ]
