# Generated by Django 4.1.12 on 2023-12-11 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamtask",
            name="memberCompleted",
            field=models.ManyToManyField(
                blank=True, related_name="completed_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
