# Generated by Django 4.1.12 on 2023-12-18 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_teamtaskcompletion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamtask",
            name="memberCompleted",
        ),
    ]
